### ISSUE TITLE
Switch to new source of DefinitelyTyped data?

### ISSUE THREAD

**Issue by karlhorky** [algolia/npm-search#1090]
It appears that Microsoft deleted the "create a search index" function in June: 

https://github.com/microsoft/DefinitelyTyped-tools/pull/456#issuecomment-1339035665

Maybe a new method is needed for determining this information:

https://github.com/algolia/npm-search/blob/d99c31fbe733953d39e498f9c7d982b2e09f3458/src/typescript/index.ts#L24-L40

One option:

Using the same algorithm that ATA uses, as mentioned by Orta https://twitter.com/orta/status/1600084654895267842

https://github.com/microsoft/TypeScript-Website/blob/f905e795350720b4a906b00155e95f370734f63c/packages/ata/src/index.ts#L63-L92

**Comment by Haroenv** [comment]
Thanks for opening this issue. Are you interested in contributing the change in source?

**Comment by jablko** [comment]
Is `pkgs` a list of all npm packages? If so, could we look there for a `@types/package` https://github.com/algolia/npm-search/blob/d99c31fbe733953d39e498f9c7d982b2e09f3458/src/typescript/index.ts#L97-L103 instead of in the obsolete https://github.com/algolia/npm-search/blob/d99c31fbe733953d39e498f9c7d982b2e09f3458/src/config.ts#L161-L162

**Comment by jablko** [comment]
Alternatively there's all-the-package-names: https://unpkg.com/all-the-package-names@2.0.476/names.json

**Comment by karlhorky** [comment]
Thanks so much @MartinKolarik and reviewers @pixelastic and @bodinsamuel for the considerable effort in #1140 🙌 

Updated the thread on Twitter:

- https://twitter.com/karlhorky/status/1711424681591398701
