### ISSUE TITLE
add alternative name without dashes

### ISSUE THREAD

**Issue by Haroenv** [algolia/npm-search#33]
for `create-react-native-app` this should be `createreactnativeapp`. This is because it's often easier to just write it without dashes.

To remove is:

* `.`
* `-`
* `_`
* `@`
* `/`

The alternative name should have a lower relevancy score than the real name to avoid `react-native` to score above `reactnative` when you search for `reactnative`.

This should also be done for the keywords, but in that case the concatenated version can simply be added.

**Comment by ercolanelli-leo** [comment]
Just to recap the chat we had:

- Add a new attribute, which is the name fully concatenated (without `.-_@/`)
- Put this attribute in `searchableAttributes`, below the original name
- Instead of doing the `optionalFacetFilter` against the name, do it against this new attribute, using a concatenated form of the query
