### ISSUE TITLE
Use list of @types instead of doing one query per package

### ISSUE THREAD

**Issue by bodinsamuel** [algolia/npm-search#401]
There is a lot of way to do that, but one simple is this one:

Microsoft create a .json with all packages on every deploy
https://github.com/microsoft/types-publisher#create-a-search-index
https://typespublisher.blob.core.windows.net/typespublisher/data/search-index-min.json

**Comment by Haroenv** [comment]
This looks interesting! @orta, do is this URL  static and safe to use for this?

**Comment by sandersn** [comment]
(Came here after @orta asked me) Yes, the URL is static and [TypeSearch](https://microsoft.github.io/TypeSearch/) already depends on this index, so types-publisher will continue to publish it.

Please do use it; I'd rather have people discover types integrated into the rest of the ecosystem instead of going to a separate site like TypeSearch.

**Comment by bodinsamuel** [comment]
Done in #639
