### ISSUE TITLE
Packages that have been unpublished from NPM are still showing up on the package search on https://yarnpkg.com

### ISSUE THREAD

**Issue by christoffercarlsson** [algolia/npm-search#556]
Hi,

I recently started publishing new versions of my NPM packages to the GitHub Package Registry.

After I made the move I requested that all packages be unpublished from the NPM registry to avoid confusion.

However, I noticed that all of the old packages are still showing up on the https://yarnpkg.com website when I search for them. Performing the same search on the https://npmjs.com website gives no results (as expected).

Is there a way to make the Algolia search results on https://yarnpkg.com mirror those on https://npmjs.com?

Thanks!

Chris

**Comment by Haroenv** [comment]
Hmm, in general delete operations are followed because of this code: 

https://github.com/algolia/npm-search/blob/8e5fb1dd7531d342207b85e3cd37ae30d9f72873/src/watch.js#L188-L193

I guess it's possible some operations either aren't sent by npm or missed by our watcher. Do you have packages that need to be deleted explicitly? You can email me or write it here

**Comment by christoffercarlsson** [comment]
Thank you for the quick reply!

Yes, all packages listed under the `@christoffercarlsson` scope would need to be deleted in order for the search results at https://yarnpkg.com to match those at https://npmjs.com.

**Comment by Haroenv** [comment]
As a hotfix I've removed your packages from the index, but I'm not sure yet why the packages weren't deleted automatically

**Comment by christoffercarlsson** [comment]
Thank you for your help! Much appreciated 🙂
