### ISSUE TITLE
"ERROR: Optional filters inside Rules are not enabled on this application"

### ISSUE THREAD

**Issue by remy** [algolia/npm-search#557]
I'm running a local version and I'm stuck on this error (when running `yarn start`):

```
  err: AlgoliaSearchError: Optional filters inside Rules are not enabled on this application
      at success (./node_modules/algoliasearch/src/AlgoliaSearchCore.js:377:32)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
      at async Module.putDefaultSettings (file://./src/algolia/index.js:56:22)
      at async Module.run (file://./src/bootstrap.js:42:5)
      at async main (file://./src/index.js:51:3)
```

I'm wondering if I'm missing some setup in Algolia perhaps?

(this is a new clone of the repo with latest node running against a "hacker" account in Algolia)

**Comment by Haroenv** [comment]
Ah, this repo requires an enterprise account unfortunately because of some of the features we're using. What you can do is comment out these lines:

https://github.com/algolia/npm-search/blob/394cb8c3844f47b856296a922829839999090bf3/src/config.js#L96-L108

What is the use case you're looking into this repo? We already have an index which is populated by this process that you might be able to use if you don't need too many changes to the data format (we can update some things if you require)

Note also that the index size this creates is 2 million records, which would be a lot if you'd need to pay for it

**Comment by remy** [comment]
It's quite literally the client's project I'm working on needs to be able to search npm package names. We built a database with the 1.4 million package names, but it was a bit useless as the search was a simplistic `like` and it brought back a lot of unwanted results for simple searches like `"angular"`.

> We already have an index which is populated by this process that you might be able to use if you don't need too many changes to the data format (we can update some things if you require)

Is this a public resource - and if so, I'd love to know a little more about it, it's most likely exactly what they're after. A fairly basic "user entered a package" -> here's a list of matching package names.

**Comment by Haroenv** [comment]
You can email me (haroen@algolia.com) and I'll create credentials for your client, as long as there's a mention of "powered by Algolia" in the page, which normally shouldn't be an issue
