### ISSUE TITLE
Cannot get downloads for scoped packages

### ISSUE THREAD

**Issue by redox** [algolia/npm-search#6]
- https://api.npmjs.org/downloads/point/last-month/@kadira/storybook-ui -> 404
 - https://api.npmjs.org/downloads/point/last-month/%40kadira%2Fstorybook-ui -> fail?

**Comment by Haroenv** [comment]
By the way, since May approximately, it's possible to get downloads for single packages, but not multiple. So either we leave it like it's now (skip scoped packages), either we get the downloads of scoped packages one by one, increasing our requests.

* https://api.npmjs.org/downloads/point/last-month/@kadira/storybook-ui <-- works
* https://api.npmjs.org/downloads/point/last-month/@kadira/storybook-ui,algoliasearch <-- gives an error response

**Comment by vvo** [comment]
Since scoped packages are not that frequent we could do some optimisation where when we have 200 packages we sort them by scoped/non scoped. For each scoped we do 1 req, for other we do bulk.

We are already doing single requests for dependedUpon so that should be fine.
