### ISSUE TITLE
> 5 days delay in indexing

### ISSUE THREAD

**Issue by MartinKolarik** [algolia/npm-search#930]
We got a report today about a package missing from the search results (https://github.com/jsdelivr/jsdelivr/issues/18387), and I see the first release was five days ago. There was also a similar issue recently (#928). Is there anything we could do to reduce the delay?

**Comment by bodinsamuel** [comment]
yep indeed. 
It seems NPM bumped their sequence again and we are 60K updates behind. 
Not so much we can do since we need to process update sequentially.
The same issue all over again :'( 

We had lost metrics monitoring since a few weeks (and had no time to look up), I have added a more annoying alerting so that I don't skip those. 

--- 

For JsDelivr we should really sync and find not an alternative but a decent way to fallback. Could be with a secondary real time index that has no additional info combined with an internal API to refresh cache.

**Comment by MartinKolarik** [comment]
Do you know what's slowing down the indexing most? I'm wondering how the fallback would work because if you visit a page like https://www.jsdelivr.com/package/npm/quantdom it's easy, but to get there, you'd usually search at https://www.jsdelivr.com/?query=quantdom and if that returns some results, there's no way for us to know we need to fallback.

At the same time, we use jsDelivrHits for sorting the search results and also plan to add an option for filtering based on moduleTypes/styleTypes fields, so using a lighter index *always* is not an option. Would it make sense to maybe insert packages to the main index immediately, with some kind of "in progress" flag, and update it later?

**Comment by Haroenv** [comment]
The index is back up to date now, thanks for standing by!
