### ISSUE TITLE
Gracefully handle 429 responses

### ISSUE THREAD

**Issue by bk2204** [algolia/npm-search#993]
Hey,

I'm one of the engineers at GitHub responsible for the archive and raw file endpoints.  We've noticed that this tool is sometimes used to download large numbers of raw files, most of which are probably things like changelogs, at a high rate of speed.

We don't typically permit that kind of rapid, automated access to those endpoints, so usually those users end up getting served large numbers of 429 responses (one IP happened to get served over 354,000 in an hour using this tool).  In the ideal world, this tool would implement its own rate-limiting per host so that wasn't necessary, but in any event, it would at least be nice if you could notice a 429 response and stop crawling that domain for a while (our timeout is 30 minutes, but something configurable might be more to your liking).

Is it possible that such a change could be implemented?

**Comment by Haroenv** [comment]
Is there a different avenue that does allow us to access multiple files at once, so we'd go from multiple files per package to only one? https://github.com/algolia/npm-search/blob/master/src/changelog.ts#L137 Would that slow down the rate enough to be accessible @bk2204 ?

thanks for contacting us in advance!

**Comment by bk2204** [comment]
You can use the API to get access to those files, but you're also going to be limited to 5000 requests per hour (if authenticated), just like you would be to the raw file endpoints.  If you needed access to an entire revision, you could use shallow clone, partial clone, or a tarball, but I don't think the demand is sufficient in your case to request an entire full revision, since you probably just need a few files.  Pulling a full revision in that case would likely produce worse results for both you and us.

We don't have a way to provide large bulk data requests that isn't rate limited and that's intentional, since we need to prevent users from tipping over our services.

If you did nothing here, you'd continue to get 429 responses, and your data will be incomplete.  The only particular problem that we have at this moment is that we're seeing alerts for serving more 429s than we expect.  However, it might cause problems in the future, and we'd definitely appreciate a gentler approach here.

**Comment by MartinKolarik** [comment]
Since we only need to list files in the root of the repo, it seems all the requests for different name variations could be replaced with a single call like this https://api.github.com/repos/algolia/npm-search/git/trees/HEAD, reducing the number of requests from 19 to 1 per repo. I'm not sure what's the regular rate of processed updates per hour though (@bodinsamuel I'm sure you have stats for this) and the 5k API limit would probably be still too low, even though this approach would be a lot more efficient.

A while back, we were actually able to obtain an increased limit on API calls for jsDelivr services (but only API, not the raw endpoint), maybe if the requirement for the API approach was just a little over the regular limit, this would be the way. Another option would also be combining the approaches - using up to 5k requests via the API and doing the brute-force only after the API limit is reached.

**Comment by MartinKolarik** [comment]
@bk2204 I believe this has been partially improved already by not making the requests in some cases, but I'm looking into adding a further rate limit here. Do you have any suggestion as to what number of requests per second to `https://raw.githubusercontent.com/` would be acceptable and avoid the 429 responses?

**Comment by bk2204** [comment]
The number of acceptable requests per hour per IP is 5000 to that service.  That number includes requests to `raw.githubusercontent.com` as well as autogenerated archives (tarballs and zipballs).  Beyond that, requests can be served a 429 and may be automatically blocked for a period (which I believe is 30 minutes) once that happens.

Your 5000 requests can be spread out over the hour or in a short burst over a few minutes; we're not very particular.  Since there are 3600 seconds in an hour, that's about 83 per minute if you want to measure it that way.
